using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using AdaptiveExpressions.Properties;
using Lucene.Net.Store;
using Microsoft.Bot.Builder;
using Microsoft.Bot.Builder.AI.QnA;
using Microsoft.Bot.Builder.Dialogs;
using Microsoft.Bot.Builder.Dialogs.Declarative.Resources;
using Microsoft.Bot.Builder.TraceExtensions;
using Microsoft.Bot.Schema;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Iciclecreek.Bot.Builder.Dialogs.Recognizers.QLucene
{
    public class QLuceneRecognizer : Recognizer
    {
        private object _monitor = new object();

        private const string IntentPrefix = "intent=";

        /// The value type for a QnAMaker trace activity.
        /// </summary>
        public const string TraceType = "https://www.iciclecreek.com/schemas/trace";

        /// <summary>
        /// The context label for a QnAMaker trace activity.
        /// </summary>
        public const string TraceLabel = "QLuceneRecognizer Trace";

        public const string QnAMatchIntent = "QnAMatch";

        public const string Kind = "Iciclecreek.QLuceneRecognizer";

        public QLuceneRecognizer()
        {

        }

        /// <summary>
        /// Create recognizer from qnaJson
        /// </summary>
        /// <param name="json"></param>
        public QLuceneRecognizer(string knowledgebase, string json)
        {
            if (json != null)
            {
                this.KnowledgeBase = knowledgebase;
                QLuceneEngineCache.GetEngine(this.KnowledgeBase, json);
            }
        }

        /// <summary>
        /// Create QLuceneRecognizer from prebuild FSDirectory
        /// </summary>
        /// <param name="dirInfo"></param>
        public QLuceneRecognizer(string knowledgeBase, DirectoryInfo dirInfo)
        {
            this.KnowledgeBase = knowledgeBase;
            QLuceneEngineCache.GetEngine(this.KnowledgeBase, () => FSDirectory.Open(dirInfo));
        }


        /// <summary>
        /// Knowledge base QNA file name. Example: foo.en-us.qna
        /// </summary>
        /// <remarks>This will look for the foo.en-us.qna.json or foo.en-us.qna.catalog as generated by QLuBuild.</remarks>
        [JsonProperty("knowledgeBase")]
        public string KnowledgeBase { get; set; }

        /// <summary>
        /// Gets or sets the whether to include the dialog name metadata for QnA context.
        /// </summary>
        /// <value>
        /// A bool or boolean expression.
        /// </value>
        [DefaultValue(false)]
        [JsonProperty("includeDialogNameInMetadata")]
        public BoolExpression IncludeDialogNameInMetadata { get; set; } = false;

        /// <summary>
        /// Gets or sets an expression to evaluate to set additional metadata name value pairs.
        /// </summary>
        /// <value>An expression to evaluate for pairs of metadata.</value>
        [JsonProperty("strictFilters")]
        public ArrayExpression<Metadata> StrictFilters { get; set; }

        /// <summary>
        /// Gets or sets an expression to evaluate to set the context.
        /// </summary>
        /// <value>An expression to evaluate to QnARequestContext to pass as context.</value>
        [JsonProperty("context")]
        public ObjectExpression<QnARequestContext> Context { get; set; }

        /// <summary>
        /// Gets or sets the threshold score to filter results.
        /// </summary>
        /// <value>
        /// The threshold for the results.
        /// </value>
        [DefaultValue(0.3F)]
        [JsonProperty("threshold")]
        public NumberExpression Threshold { get; set; } = 0.3F;

        /// <summary>
        /// Gets or sets the rankerType.
        /// </summary>
        /// <value>If QuestionOnly, only questions will be matched.</value>
        [JsonProperty("rankerType")]
        public StringExpression RankerType { get; set; }

        /// <summary>
        /// Gets or sets the StrictFiltersCompountOperationType.
        /// </summary>
        /// <value>Set to AND or OR for boolean operator to use to combine strict filters.  Default is AND</value>
        [JsonProperty("strictFiltersCompoundOperationType")]
        public StringExpression StrictFiltersCompoundOperationType { get; set; }

        public async override Task<RecognizerResult> RecognizeAsync(DialogContext dialogContext, Activity activity, CancellationToken cancellationToken = default, Dictionary<System.String, System.String> telemetryProperties = null, Dictionary<System.String, System.Double> telemetryMetrics = null)
        {
            var qluceneEngine = await QLuceneEngineCache.GetEngine(dialogContext, this.KnowledgeBase).ConfigureAwait(false);

            var threshold = Threshold.GetValue(dialogContext);
            var recognizerResult = new RecognizerResult
            {
                Text = activity.Text,
                Intents = new Dictionary<string, IntentScore>(),
            };

            if (string.IsNullOrEmpty(activity.Text))
            {
                recognizerResult.Intents.Add("None", new IntentScore());
                return recognizerResult;
            }
            var rankerType = RankerType?.GetValue(dialogContext.State);
            var strictFiltersCompoundOperationType = StrictFiltersCompoundOperationType?.GetValue(dialogContext.State);
            var strictFilters = new List<Metadata>();
            var context = Context?.GetValue(dialogContext.State);
            bool includeDialogNameInMetadata = IncludeDialogNameInMetadata.GetValue(dialogContext.State);
            if (includeDialogNameInMetadata)
            {
                strictFilters.Add(new Metadata
                {
                    Name = "dialogName",
                    Value = dialogContext.ActiveDialog.Id
                });
            }

            // if there is $qna.metadata set add to filters
            var externalMetadata = StrictFilters?.GetValue(dialogContext.State);
            if (externalMetadata != null)
            {
                strictFilters.AddRange(externalMetadata);
            }

            var topAnswer = qluceneEngine.GetAnswers(activity.Text,
                strictFilters: strictFilters.ToArray(),
                context: context,
                threshold: threshold,
                rankerType: rankerType,
                strictFiltersCompoundOperationType: strictFiltersCompoundOperationType);

            if (topAnswer != null)
            {
                if (topAnswer.Answer.Trim().ToUpperInvariant().StartsWith(IntentPrefix.ToUpperInvariant(), StringComparison.Ordinal))
                {
                    recognizerResult.Intents.Add(topAnswer.Answer.Trim().Substring(IntentPrefix.Length).Trim(), new IntentScore { Score = topAnswer.Score });
                }
                else
                {
                    recognizerResult.Intents.Add(QnAMatchIntent, new IntentScore { Score = topAnswer.Score });
                }

                var answerArray = new JArray();
                answerArray.Add(topAnswer.Answer);
                ObjectPath.SetPathValue(recognizerResult, "entities.answer", answerArray);

                var instance = new JArray();
                var data = JObject.FromObject(topAnswer);
                data["startIndex"] = 0;
                data["endIndex"] = activity.Text.Length;
                instance.Add(data);
                ObjectPath.SetPathValue(recognizerResult, "entities.$instance.answer", instance);

                // recognizerResult.Properties["answers"] = answers;
            }
            else
            {
                recognizerResult.Intents.Add("None", new IntentScore { Score = 1.0f });
            }

            var traceInfo = new
            {
                recognizerResult,
                options = new
                {
                    id = this.Id,
                    knowledgeBase = this.KnowledgeBase,
                    scoreThreshold = threshold,
                    context,
                    rankerType,
                    strictFilters = strictFilters.ToArray(),
                    includeDialogNameInMetadata,
                    strictFiltersCompoundOperationType
                }
            };

            await dialogContext.Context.TraceActivityAsync(nameof(QLuceneRecognizer), traceInfo, TraceType, TraceLabel, cancellationToken).ConfigureAwait(false);
            return recognizerResult;
        }
    }
}
